"""empty message

Revision ID: 03bce29d98e6
Revises: 1ea94d4479e2
Create Date: 2020-10-21 17:13:05.018911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bce29d98e6'
down_revision = '1ea94d4479e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'approved')
    # ### end Alembic commands ###
