"""empty message

Revision ID: 1b2f8e740bfa
Revises: 87e07818074b
Create Date: 2021-01-07 16:10:41.992746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2f8e740bfa'
down_revision = '87e07818074b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('section_id', sa.Integer(), nullable=True))
    op.drop_constraint('enrollment_class_id_fkey', 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'section', ['section_id'], ['id'])
    op.drop_column('enrollment', 'class_id')
    op.add_column('exam', sa.Column('section_id', sa.Integer(), nullable=True))
    op.drop_constraint('exam_section_fkey', 'exam', type_='foreignkey')
    op.create_foreign_key(None, 'exam', 'section', ['section_id'], ['id'])
    op.drop_column('exam', 'section')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('section', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.create_foreign_key('exam_section_fkey', 'exam', 'section', ['section'], ['id'])
    op.drop_column('exam', 'section_id')
    op.add_column('enrollment', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key('enrollment_class_id_fkey', 'enrollment', 'class', ['class_id'], ['id'])
    op.drop_column('enrollment', 'section_id')
    # ### end Alembic commands ###
