"""empty message

Revision ID: 20bf52a0ba4e
Revises: 9f313f711e4b
Create Date: 2021-01-06 17:56:38.433420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bf52a0ba4e'
down_revision = '9f313f711e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('exam', sa.Column('section', sa.Integer(), nullable=True))
    op.drop_constraint('exam_class_id_fkey', 'exam', type_='foreignkey')
    op.create_foreign_key(None, 'exam', 'section', ['section'], ['id'])
    op.drop_column('exam', 'class_id')
    op.add_column('user', sa.Column('ta', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('teacher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'teacher')
    op.drop_column('user', 'ta')
    op.add_column('exam', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.create_foreign_key('exam_class_id_fkey', 'exam', 'class', ['class_id'], ['id'])
    op.drop_column('exam', 'section')
    op.drop_table('section')
    # ### end Alembic commands ###
