"""empty message

Revision ID: 28aa8d844d05
Revises: 815a1564a253
Create Date: 2020-10-27 21:42:27.207401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28aa8d844d05'
down_revision = '815a1564a253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('cumulative', sa.Boolean(), nullable=True))
    op.add_column('exam', sa.Column('exam_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'exam_number')
    op.drop_column('exam', 'cumulative')
    # ### end Alembic commands ###
