"""empty message

Revision ID: 2a39a490ee90
Revises: e035cf4205a1
Create Date: 2020-10-23 18:14:44.304422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a39a490ee90'
down_revision = 'e035cf4205a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exams', sa.Integer(), nullable=True),
    sa.Column('quizzes', sa.Integer(), nullable=True),
    sa.Column('final_exam', sa.Boolean(), nullable=True),
    sa.Column('final_exam_cumulative', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_structure')
    # ### end Alembic commands ###
