"""empty message

Revision ID: 31f1a3874063
Revises: 3746b3ad7182
Create Date: 2020-10-30 20:07:07.904022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f1a3874063'
down_revision = '3746b3ad7182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_exam_topic', sa.Column('exam_topic_id', sa.Integer(), nullable=True))
    op.drop_constraint('follow_exam_topic_exam_topics_id_fkey', 'follow_exam_topic', type_='foreignkey')
    op.create_foreign_key(None, 'follow_exam_topic', 'exam_topics', ['exam_topic_id'], ['id'])
    op.drop_column('follow_exam_topic', 'exam_topics_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_exam_topic', sa.Column('exam_topics_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'follow_exam_topic', type_='foreignkey')
    op.create_foreign_key('follow_exam_topic_exam_topics_id_fkey', 'follow_exam_topic', 'exam_topics', ['exam_topics_id'], ['id'])
    op.drop_column('follow_exam_topic', 'exam_topic_id')
    # ### end Alembic commands ###
