"""empty message

Revision ID: 34402d0e1bc7
Revises: e4a8f859a0b9
Create Date: 2021-01-07 18:03:56.358650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34402d0e1bc7'
down_revision = 'e4a8f859a0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'approved')
    # ### end Alembic commands ###
