"""empty message

Revision ID: 356d721e2b97
Revises: 8839d1d06810
Create Date: 2020-10-29 22:11:59.826400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356d721e2b97'
down_revision = '8839d1d06810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionanswerargument', sa.Column('other_explanation_clicks', sa.Integer(), nullable=True))
    op.drop_column('questionanswerargument', 'argument_votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionanswerargument', sa.Column('argument_votes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('questionanswerargument', 'other_explanation_clicks')
    # ### end Alembic commands ###
