"""empty message

Revision ID: 3746b3ad7182
Revises: 356d721e2b97
Create Date: 2020-10-30 19:23:40.982555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3746b3ad7182'
down_revision = '356d721e2b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow_exam_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_topics_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_topics_id'], ['exam_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow_exam_topic')
    # ### end Alembic commands ###
