"""empty message

Revision ID: 4df44507d481
Revises: 59f872709636
Create Date: 2020-10-17 18:37:11.197229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df44507d481'
down_revision = '59f872709636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=40), nullable=True),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QuestionTopics',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.add_column('question', sa.Column('subject', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'subject', ['subject'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'subject')
    op.drop_table('QuestionTopics')
    op.drop_table('topic')
    op.drop_table('subject')
    # ### end Alembic commands ###
