"""empty message

Revision ID: 5532ee26ebf5
Revises: 1b2f8e740bfa
Create Date: 2021-01-07 16:40:44.873052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5532ee26ebf5'
down_revision = '1b2f8e740bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('description', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('section', 'description')
    # ### end Alembic commands ###
