"""empty message

Revision ID: 59f872709636
Revises: ba0bfedf7476
Create Date: 2020-10-17 16:29:39.290371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f872709636'
down_revision = 'ba0bfedf7476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_question_timestamp', table_name='question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_question_timestamp', 'question', ['timestamp'], unique=False)
    op.drop_table('answer')
    # ### end Alembic commands ###
