"""empty message

Revision ID: 751f5ee9f449
Revises: acbb5846c612
Create Date: 2021-03-10 20:40:32.449495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751f5ee9f449'
down_revision = 'acbb5846c612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_set_term', sa.Column('interaction_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_set_term', 'interaction_count')
    # ### end Alembic commands ###
