"""empty message

Revision ID: 7a66f78d0551
Revises: 07fca8558b6c
Create Date: 2021-01-09 23:53:55.437557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a66f78d0551'
down_revision = '07fca8558b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam', 'start_time')
    # ### end Alembic commands ###
