"""empty message

Revision ID: 815a1564a253
Revises: fc55f80c29e8
Create Date: 2020-10-27 21:24:33.969166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815a1564a253'
down_revision = 'fc55f80c29e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_structure_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exam_count', sa.Integer(), nullable=True),
    sa.Column('quiz_count', sa.Integer(), nullable=True),
    sa.Column('final_exam', sa.Boolean(), nullable=True),
    sa.Column('final_exam_cumulative', sa.Boolean(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_structure_suggestion')
    # ### end Alembic commands ###
