"""empty message

Revision ID: 824052217510
Revises: 4df44507d481
Create Date: 2020-10-17 20:56:55.425080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824052217510'
down_revision = '4df44507d481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_topics',
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    op.drop_table('QuestionTopics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('QuestionTopics',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='QuestionTopics_question_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='QuestionTopics_topic_id_fkey')
    )
    op.drop_table('question_topics')
    # ### end Alembic commands ###
