"""empty message

Revision ID: 8839d1d06810
Revises: 28aa8d844d05
Create Date: 2020-10-27 21:55:48.673862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8839d1d06810'
down_revision = '28aa8d844d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_structure_suggestion', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_structure_suggestion', 'approved')
    # ### end Alembic commands ###
