"""empty message

Revision ID: 8b68d35204ac
Revises: e99d9bf2b317
Create Date: 2020-10-23 12:18:13.304454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b68d35204ac'
down_revision = 'e99d9bf2b317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionanswerargument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('argument_votes', sa.Integer(), nullable=True),
    sa.Column('argument_evaluations', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionanswerargumentreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_answer_argument_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_answer_argument_id'], ['questionanswerargument.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_answer_argument')
    op.drop_table('question_answer_argument_report')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_answer_argument_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='question_answer_argument_report_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_answer_argument_report_pkey')
    )
    op.create_table('question_answer_argument',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.Column('argument_votes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('argument_evaluations', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='question_answer_argument_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_answer_argument_pkey')
    )
    op.drop_table('questionanswerargumentreport')
    op.drop_table('questionanswerargument')
    # ### end Alembic commands ###
