"""empty message

Revision ID: 98f8517c8730
Revises: 2a39a490ee90
Create Date: 2020-10-23 18:30:06.186225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f8517c8730'
down_revision = '2a39a490ee90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_structure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_structure',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exams', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quizzes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_exam', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('final_exam_cumulative', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], name='exam_structure_class_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='exam_structure_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_structure_pkey')
    )
    # ### end Alembic commands ###
