"""empty message

Revision ID: 9f313f711e4b
Revises: e8518f2ac50c
Create Date: 2020-12-09 15:58:21.007424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f313f711e4b'
down_revision = 'e8518f2ac50c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_set_term', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'study_set_term', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'study_set_term', type_='foreignkey')
    op.drop_column('study_set_term', 'user_id')
    # ### end Alembic commands ###
