"""empty message

Revision ID: acbb5846c612
Revises: e85d7f33c8ec
Create Date: 2021-03-08 21:20:06.776002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbb5846c612'
down_revision = 'e85d7f33c8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_set_term', sa.Column('saved_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_set_term', 'saved_status')
    # ### end Alembic commands ###
