"""empty message

Revision ID: d00b16d17dce
Revises: 8b68d35204ac
Create Date: 2020-10-23 12:19:53.078005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00b16d17dce'
down_revision = '8b68d35204ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('answer_selections', sa.Integer(), nullable=True),
    sa.Column('answer_presentations', sa.Integer(), nullable=True),
    sa.Column('correctness_score', sa.Integer(), nullable=True),
    sa.Column('correctness_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('question_answer')
    op.add_column('questionanswerargument', sa.Column('question_answer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questionanswerargument', 'questionanswer', ['question_answer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionanswerargument', type_='foreignkey')
    op.drop_column('questionanswerargument', 'question_answer_id')
    op.create_table('question_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_selections', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_presentations', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correctness_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('correctness_votes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.id'], name='question_answer_answer_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='question_answer_question_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='question_answer_pkey')
    )
    op.drop_table('questionanswer')
    # ### end Alembic commands ###
