"""empty message

Revision ID: d70207aa7244
Revises: 03bce29d98e6
Create Date: 2020-10-21 17:52:01.669531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70207aa7244'
down_revision = '03bce29d98e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subject', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subject', type_='foreignkey')
    op.drop_column('subject', 'user_id')
    # ### end Alembic commands ###
