"""empty message

Revision ID: d8f444b19f47
Revises: b575c53b2c82
Create Date: 2020-10-18 12:26:09.604046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f444b19f47'
down_revision = 'b575c53b2c82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('description', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'description')
    # ### end Alembic commands ###
