"""empty message

Revision ID: e035cf4205a1
Revises: d00b16d17dce
Create Date: 2020-10-23 14:47:22.919930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e035cf4205a1'
down_revision = 'd00b16d17dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('description', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic', 'description')
    # ### end Alembic commands ###
