"""empty message

Revision ID: e4a8f859a0b9
Revises: 5532ee26ebf5
Create Date: 2021-01-07 17:21:31.193303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a8f859a0b9'
down_revision = '5532ee26ebf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'enrollment', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.drop_column('enrollment', 'class_id')
    # ### end Alembic commands ###
