"""empty message

Revision ID: f1e4404249c7
Revises: 824052217510
Create Date: 2020-10-17 21:06:28.044423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e4404249c7'
down_revision = '824052217510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_topics')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_topics',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='question_topics_question_id_fkey'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='question_topics_topic_id_fkey')
    )
    # ### end Alembic commands ###
