"""empty message

Revision ID: fc55f80c29e8
Revises: 1dd140dd5a3e
Create Date: 2020-10-27 21:07:55.634201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc55f80c29e8'
down_revision = '1dd140dd5a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class', sa.Column('readable', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class', 'readable')
    # ### end Alembic commands ###
